# Generated by Django 4.1.7 on 2024-08-03 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
