# Generated by Django 4.1.7 on 2024-08-04 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanagement', '0004_alter_student_class_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studentmanagement.class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
